//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    
    public class CompanyViewModel
    {
        
        public long Id;
        
        public string Name;
        
        public ICollection<CompactRoomViewModel> Rooms;
        
        public ICollection<CompactEmployeeViewModel> Employees;
    }
}
