//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    
    public class CompanyViewModel
    {
        
        private long _Id;
        
        private string _Name;
        
        private ICollection<CompactRoomViewModel> _Rooms;
        
        private ICollection<CompactEmployeeViewModel> _Employees;
        
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }
        
        public ICollection<CompactRoomViewModel> Rooms
        {
            get
            {
                return this._Rooms;
            }
            set
            {
                this._Rooms = value;
            }
        }
        
        public ICollection<CompactEmployeeViewModel> Employees
        {
            get
            {
                return this._Employees;
            }
            set
            {
                this._Employees = value;
            }
        }
    }
}
