//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    
    public class RoomViewModel
    {
        
        private long _Id;
        
        private string _Name;
        
        private CompactCompanyViewModel _Company;
        
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }
        
        public CompactCompanyViewModel Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
            }
        }
    }
}
