//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public class Employee
    {
        
        private int _Id;
        
        private string _FirstName;
        
        private Company _Company;
        
        private Department _Department;
        
        private Branch _Branch;
        
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this._FirstName = value;
            }
        }
        
        public Company Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
            }
        }
        
        public Department Department
        {
            get
            {
                return this._Department;
            }
            set
            {
                this._Department = value;
            }
        }
        
        public Branch Branch
        {
            get
            {
                return this._Branch;
            }
            set
            {
                this._Branch = value;
            }
        }
    }
}
